{
 "title": "Home data",
 "time": { "from": "2024-03-22T22:00:00.000Z", "to": "2024-03-25T18:31:08.943Z" },
 "panels": [
  {
   "title": "Plug 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "queryText": "WITH converted AS (\n   SELECT off_on,device_id, power, energy, strftime('%Y-%m-%dT%H:%M:%SZ', record_time) AS datetime\n   FROM shelly_data WHERE device_id = 1\n)\nSELECT datetime, off_on, power, energy \nFROM converted\nORDER BY datetime ASC",
     "rawQueryText": "WITH converted AS (\n   SELECT off_on,device_id, power, energy, strftime('%Y-%m-%dT%H:%M:%SZ', record_time) AS datetime\n   FROM shelly_data WHERE device_id = 1\n)\nSELECT datetime, off_on, power, energy \nFROM converted\nORDER BY datetime ASC",
     "timeColumns": [ "datetime" ]
    }
   ]
  },
  {
   "title": "Plug 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "queryText": "WITH converted AS (\n   SELECT off_on,device_id, power, energy, strftime('%Y-%m-%dT%H:%M:%SZ', record_time) AS datetime\n   FROM shelly_data WHERE device_id = 2\n)\nSELECT datetime, off_on, power, energy \nFROM converted \nORDER BY datetime ASC",
     "rawQueryText": "WITH converted AS (\n   SELECT off_on,device_id, power, energy, strftime('%Y-%m-%dT%H:%M:%SZ', record_time) AS datetime\n   FROM shelly_data WHERE device_id = 2\n)\nSELECT datetime, off_on, power, energy \nFROM converted \nORDER BY datetime ASC",
     "timeColumns": [ "datetime" ]
    }
   ]
  },
  {
   "title": "Relay 1 SHELLY PLUS 1 PM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "queryText": "WITH converted AS (\n   SELECT voltage, current, off_on,device_id, power, energy, strftime('%Y-%m-%dT%H:%M:%SZ', record_time) AS datetime\n   FROM shelly_data WHERE device_id = 4\n)\nSELECT datetime, off_on, power, energy, voltage, current\nFROM converted \nORDER BY datetime ASC",
     "rawQueryText": "WITH converted AS (\n   SELECT voltage, current, off_on,device_id, power, energy, strftime('%Y-%m-%dT%H:%M:%SZ', record_time) AS datetime\n   FROM shelly_data WHERE device_id = 4\n)\nSELECT datetime, off_on, power, energy, voltage, current\nFROM converted \nORDER BY datetime ASC",
     "timeColumns": [ "datetime" ]
    }
   ]
  },
  {
   "title": "Temperatures AHU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "queryText": "WITH converted AS (\n   SELECT value, device_id, strftime('%Y-%m-%dT%H:%M:%SZ', record_time) AS datetime\n   FROM sensor_data \n)\nSELECT datetime, value AS supply\nFROM converted \nWHERE device_id IN (6)\nGROUP BY datetime, device_id\nORDER BY datetime ASC",
     "rawQueryText": "WITH converted AS (\n   SELECT value, device_id, strftime('%Y-%m-%dT%H:%M:%SZ', record_time) AS datetime\n   FROM sensor_data \n)\nSELECT datetime, value AS supply\nFROM converted \nWHERE device_id IN (6)\nGROUP BY datetime, device_id\nORDER BY datetime ASC",
     "timeColumns": [ "datetime" ]
    },
    {
     "queryText": "WITH converted AS (\n   SELECT value, device_id, strftime('%Y-%m-%dT%H:%M:%SZ', record_time) AS datetime\n   FROM sensor_data \n)\nSELECT datetime, value AS indoor\nFROM converted \nWHERE device_id IN (4)\nGROUP BY datetime, device_id\nORDER BY datetime ASC",
     "rawQueryText": "WITH converted AS (\n   SELECT value, device_id, strftime('%Y-%m-%dT%H:%M:%SZ', record_time) AS datetime\n   FROM sensor_data \n)\nSELECT datetime, value AS indoor\nFROM converted \nWHERE device_id IN (4)\nGROUP BY datetime, device_id\nORDER BY datetime ASC",
     "timeColumns": [ "datetime" ]
    },
    {
     "queryText": "WITH converted AS (\n   SELECT value, device_id, strftime('%Y-%m-%dT%H:%M:%SZ', record_time) AS datetime\n   FROM sensor_data \n)\nSELECT datetime, value AS outdoor\nFROM converted \nWHERE device_id IN (5)\nGROUP BY datetime, device_id\nORDER BY datetime ASC",
     "rawQueryText": "WITH converted AS (\n   SELECT value, device_id, strftime('%Y-%m-%dT%H:%M:%SZ', record_time) AS datetime\n   FROM sensor_data \n)\nSELECT datetime, value AS outdoor\nFROM converted \nWHERE device_id IN (5)\nGROUP BY datetime, device_id\nORDER BY datetime ASC",
     "timeColumns": [ "datetime" ]
    },
    {
     "queryText": "WITH converted AS (\n   SELECT value, device_id, strftime('%Y-%m-%dT%H:%M:%SZ', record_time) AS datetime\n   FROM sensor_data \n)\nSELECT datetime, value AS exhaust\nFROM converted \nWHERE device_id IN (7)\nGROUP BY datetime, device_id\nORDER BY datetime ASC",
     "rawQueryText": "WITH converted AS (\n   SELECT value, device_id, strftime('%Y-%m-%dT%H:%M:%SZ', record_time) AS datetime\n   FROM sensor_data \n)\nSELECT datetime, value AS exhaust\nFROM converted \nWHERE device_id IN (7)\nGROUP BY datetime, device_id\nORDER BY datetime ASC",
     "timeColumns": [ "datetime" ]
    }
   ]
  },
  {
   "title": "Prices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "queryText": "WITH converted AS (\r\n   SELECT price,  date || 'T' || printf('%02d', hour) || ':00:00Z' AS datetime \r\n   FROM prices \r\n   --WHERE date >= date('now', '-2 days')\r\n)\r\nSELECT datetime, price FROM converted ORDER BY datetime ASC",
     "rawQueryText": "WITH converted AS (\r\n   SELECT price,  date || 'T' || printf('%02d', hour) || ':00:00Z' AS datetime \r\n   FROM prices \r\n   --WHERE date >= date('now', '-2 days')\r\n)\r\nSELECT datetime, price FROM converted ORDER BY datetime ASC",
     "timeColumns": [ "datetime" ]
    }
   ]
  },
  {
   "title": "Prices w relay 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "EUR/MWh" } },
   "targets": [
    {
     "queryText": "WITH converted AS (\n   SELECT off_on,power, strftime('%Y-%m-%dT%H:%M:%SZ', record_time) AS datetime\n   FROM shelly_data WHERE device_id = 1\n)\nSELECT off_on, power, datetime\nFROM converted \nORDER BY datetime ASC",
     "rawQueryText": "WITH converted AS (\n   SELECT off_on,power, strftime('%Y-%m-%dT%H:%M:%SZ', record_time) AS datetime\n   FROM shelly_data WHERE device_id = 1\n)\nSELECT off_on, power, datetime\nFROM converted \nORDER BY datetime ASC",
     "timeColumns": [ "datetime" ]
    },
    {
     "queryText": "WITH converted AS (\r\n   SELECT price,  date || 'T' || printf('%02d', hour) || ':00:00Z' AS datetime \r\n   FROM prices \r\n   --WHERE date >= date('now', '-2 days')\r\n)\r\nSELECT datetime, price FROM converted ORDER BY datetime ASC",
     "rawQueryText": "WITH converted AS (\r\n   SELECT price,  date || 'T' || printf('%02d', hour) || ':00:00Z' AS datetime \r\n   FROM prices \r\n   --WHERE date >= date('now', '-2 days')\r\n)\r\nSELECT datetime, price FROM converted ORDER BY datetime ASC",
     "timeColumns": [ "datetime" ]
    }
   ]
  },
  {
   "title": "Air quality",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "queryText": "WITH converted AS (\n   SELECT value, device_id, strftime('%Y-%m-%dT%H:%M:%SZ', record_time) AS datetime\n   FROM sensor_data \n)\nSELECT datetime, value AS speed\nFROM converted \nWHERE device_id IN (1)\nGROUP BY datetime, device_id\nORDER BY datetime ASC",
     "rawQueryText": "WITH converted AS (\n   SELECT value, device_id, strftime('%Y-%m-%dT%H:%M:%SZ', record_time) AS datetime\n   FROM sensor_data \n)\nSELECT datetime, value AS speed\nFROM converted \nWHERE device_id IN (1)\nGROUP BY datetime, device_id\nORDER BY datetime ASC",
     "timeColumns": [ "datetime" ]
    },
    {
     "queryText": "WITH converted AS (\n   SELECT value, device_id, strftime('%Y-%m-%dT%H:%M:%SZ', record_time) AS datetime\n   FROM sensor_data \n)\nSELECT datetime, value AS humidity\nFROM converted \nWHERE device_id IN (2)\nGROUP BY datetime, device_id\nORDER BY datetime ASC",
     "rawQueryText": "WITH converted AS (\n   SELECT value, device_id, strftime('%Y-%m-%dT%H:%M:%SZ', record_time) AS datetime\n   FROM sensor_data \n)\nSELECT datetime, value AS humidity\nFROM converted \nWHERE device_id IN (2)\nGROUP BY datetime, device_id\nORDER BY datetime ASC",
     "timeColumns": [ "datetime" ]
    },
    {
     "queryText": "WITH converted AS (\n   SELECT value, device_id, strftime('%Y-%m-%dT%H:%M:%SZ', record_time) AS datetime\n   FROM sensor_data \n)\nSELECT datetime, value AS co2\nFROM converted \nWHERE device_id IN (3)\nGROUP BY datetime, device_id\nORDER BY datetime ASC",
     "rawQueryText": "WITH converted AS (\n   SELECT value, device_id, strftime('%Y-%m-%dT%H:%M:%SZ', record_time) AS datetime\n   FROM sensor_data \n)\nSELECT datetime, value AS co2\nFROM converted \nWHERE device_id IN (3)\nGROUP BY datetime, device_id\nORDER BY datetime ASC",
     "timeColumns": [ "datetime" ]
    }
   ]
  }
 ]
}